### ISSUE TITLE
Localizated Labels

### ISSUE THREAD

**Issue by dunqi** [mapbox/MapboxStatic.swift#72]
Hello,

is there a opportunity to change the label localization like in MapBox?

thanks

**Comment by 1ec5** [comment]
Not programmatically, because the Static API doesn’t expose the full runtime styling API. However, you can [customize a style in Mapbox Studio](https://www.mapbox.com/help/change-language/#change-label-language-in-mapbox-studio) to use the language of your choice, then pass the style’s URL into `SnapshotOptions(styleURL:size:)`.
